apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    app: data-volume
  name: img-linux-iso
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  source:
    http:
      url: http://minio.minio-ecpaas.svc:9000/ecpaas-images/ubuntu-20.04.5-live-server-amd64.iso

