apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: linux-iso-test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-20.04.5-live-server-amd64
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - cdrom:
              bus: sata
            name: ins-iso
            bootOrder: 2
          - disk:
              bus: virtio
            name: linux-iso-drive
            bootOrder: 1
          interfaces:
          - name: default
            model: virtio
            bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: ins-iso
        persistentVolumeClaim:
          claimName: img-linux-iso
      - name: linux-iso-drive
        persistentVolumeClaim:
          claimName: linux-drive
        